using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

namespace RM_EDU
{
    // An action player.
    public abstract class ActionPlayer : MonoBehaviour
    {
        // The action manager.
        public ActionManager actionManager;

        // The action unit prefabs.
        public ActionUnitPrefabs actionUnitPrefabs;

        // The amount of energy the player has.
        public float energy = 0;

        // The amount of air pollution the player has generated.
        public float airPollution = 0;

        // The parent of the units created by the player.
        public GameObject unitParent;

        // The parent for projectiles generated by units from this player.
        public GameObject unitProjectileParent;

        // The number of kills this player has.
        public int kills = 0;

        // Gets set to 'true' if the player is blocking energy from defense units trying to attack.
        // If blocking energy, units that use energy to attack cannot take from the player's energy.
        // If a unit uses no energy for attacking, it can still attack.
        [Tooltip("If true, the player is blocking energy that's used for attacks, preventing defenses that use energy from attacking.")]
        public bool blockingAttackEnergy = false;

        // If audio is enabled for this player.
        protected bool audioEnabled = true;

        // Start is called before the first frame update
        protected virtual void Start()
        {
            // If the action manager is null, get the action manager.
            if (actionManager == null)
                actionManager = ActionManager.Instance;

            // The action unit prefabs.
            if (actionUnitPrefabs == null)
                actionUnitPrefabs = ActionUnitPrefabs.Instance;

            // If the unit parent is null, make this object the unit parent.
            if (unitParent == null)
                unitParent = gameObject;

            // If the unit projectile parent isn't set, treat this object as the parent.
            if (unitProjectileParent == null)
                unitProjectileParent = gameObject;
        }

        // Returns 'true' if the action player can create a unit with the provided energy cost.
        public bool CanCreateActionUnit(float energyCreationCost)
        {
            return energyCreationCost <= energy;
        }

        // Returns 'true' if the action player can create the provided action unit.
        public bool CanCreateActionUnit(ActionUnit actionUnit)
        {
            return CanCreateActionUnit(actionUnit.energyCreationCost);
        }

        // Sets the action unit parent to the unit parent object.
        // If 'thisParentIfNull' is true, this is set as the unit's parent if the unit parent object is null.
        public virtual void SetActionUnitParentToUnitParent(ActionUnit actionUnit, bool thisParentIfNull = true)
        {
            // If there's a dedicated unit parent, give it that as the parent.
            if (unitParent != null)
            {
                actionUnit.transform.parent = unitParent.transform;
            }
            // No unit parent, so make this object the parent of the enemy unit.
            else
            {
                actionUnit.transform.parent = (thisParentIfNull) ? transform : null;
            }
        }


        // ENERGY //
        // Returns 'true' if the player has energy.
        public bool HasEnergy()
        {
            return energy > 0.0F;
        }

        // Modifies the energy by adding the provided amount.
        public virtual void IncreaseEnergy(float energyPlus)
        {
            // Add energy.
            energy += energyPlus;

            // Bounds check.
            if (energy < 0.0F)
                energy = 0.0F;
        }

        // Decreses the energy by the provided amount.
        public virtual void DecreaseEnergy(float energyMinus)
        {
            // Reduce energy.
            energy -= energyMinus;

            // Bounds check.
            if (energy < 0.0F)
                energy = 0.0F;
        }

        // Returns 'true' if the player has the energy to create the provided aciton unit.
        public bool HasEnergyToCreateActionUnit(ActionUnit actionUnit)
        {
            return energy >= actionUnit.energyCreationCost;
        }

        // Returns 'true' if the player has energy for the attack.
        public bool HasEnergyForAttack(ActionUnit actionUnit)
        {
            // Result to be returned.
            bool result;

            // If the player with blocking (witholding) attack energy, act as if...
            // The player has no energy for attacking.
            if(blockingAttackEnergy)
            {
                // If the action unit uses no energy for its attacks...
                // Allow the attack.
                result = actionUnit.attackEnergyCost <= 0;
            }
            else
            {
                // The player isn't blocking (witholding) energy for attacks...
                // So if the player has enough energy to attack.
                result = energy >= actionUnit.attackEnergyCost;
            }

            return result;                
        }

        // AIR POLLUTION //
        // Returns 'ture' if the user has air pollution.
        public bool HasAirPollution()
        {
            return airPollution > 0;
        }

        // Increases the air pollution by the provided amount.
        public void IncreaseAirPollution(float increase)
        {
            airPollution += increase;

            // Bounds check.
            if (airPollution < 0)
                airPollution = 0;
        }

        // Decreases the air pollution by the provided amount.
        public void DecreaseAirPollution(float decrease)
        {
            airPollution -= decrease;

            // Bounds check.
            if(airPollution < 0)
                airPollution = 0;
        }

        // Resets the air pollution amount.
        public void ResetAirPollution()
        {
            airPollution = 0;
        }

        // KILLS
        // Gets the kill count.
        public int GetKills()
        {
            return kills;
        }

        // Resets the kill count.
        public void ResetKills()
        {
            kills = 0;
        }

        // BLOCKING ENERGY //
        // Returns 'true' if attack energy is being blocked.
        public bool IsBlockingAttackEnergy()
        {
            return blockingAttackEnergy;
        }

        // Sets if attack energy should be blocked.
        public void SetBlockingAttackEnergy(bool blocking)
        {
            blockingAttackEnergy = blocking;
        }

        // Blocks the attack energy.
        public void BlockAttackEnergy()
        {
            SetBlockingAttackEnergy(true);
        }

        // Unblocks the attack energy.
        public void UnblockAttackEnergy()
        {
            SetBlockingAttackEnergy(false);
        }

        // Toggles blocking attack energy.
        public void ToggleBlockingAttackEnergy()
        {
            SetBlockingAttackEnergy(!blockingAttackEnergy);
        }


        // AUDIO //
        // If 'true', the audio is enabled.
        public bool IsAudioEnabled()
        {
            return audioEnabled;
        }


        // RESET //
        // Resets the player.
        public virtual void ResetPlayer()
        {
            ResetAirPollution();
            ResetKills();
        }

        // Update is called once per frame
        protected virtual void Update()
        {
            // ...
        }
    }
}